name: Wakatime Stats

concurrency:
  group: readme-update
  cancel-in-progress: false

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Wakatime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: athul/waka-readme@v0.3.1
        continue-on-error: true
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SHOW_Masked_TIME: true
          # STOP_AT_OTHER: true # Commented out to ensure all time is shown
